# Generated by Django 3.0.8 on 2020-07-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperaturemonitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempHumMeas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('temp_sensor_1', models.FloatField()),
                ('hum_sensor_1', models.FloatField()),
                ('temp_sensor_2', models.FloatField()),
                ('hum_sensor_2', models.FloatField()),
                ('temp_sensor_3', models.FloatField()),
                ('hum_sensor_3', models.FloatField()),
            ],
        ),
    ]
