# Generated by Django 3.0.8 on 2020-07-20 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperaturemonitor', '0002_temphummeas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
