# Generated by Django 3.0.8 on 2020-07-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperaturemonitor', '0003_auto_20200720_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temphummeas',
            name='hum_sensor_1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='temphummeas',
            name='hum_sensor_2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='temphummeas',
            name='hum_sensor_3',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='temphummeas',
            name='temp_sensor_1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='temphummeas',
            name='temp_sensor_2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='temphummeas',
            name='temp_sensor_3',
            field=models.FloatField(null=True),
        ),
    ]
